language: pytnon

python: "3.6"

# don't clone more deeply than necessary
git:
  depth: 1

# install dependencies
install:
  - pip install   -r requirements.txt

# run all tests
script:
  - python -m unittest discover -p "*_test.py"
